services:
  cms:
    build:
      context: ./cms
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      SERVER_URL: ${CMS_URL}
      CORS_ORIGINS: ${CLIENT_URL}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_REGION: ${S3_REGION}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cms.rule=Host(`${CMS_HOST}`)"
      - "traefik.http.routers.cms.entrypoints=websecure"
      - "traefik.http.routers.cms.tls.certresolver=${TRAEFIK_CERTRESOLVER}"
      - "traefik.http.services.cms.loadbalancer.server.port=3000"
    networks:
      - default
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        PUBLIC_PAYLOAD_URL: ${CMS_URL}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`${CLIENT_HOST}`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=${TRAEFIK_CERTRESOLVER}"
      - "traefik.http.services.client.loadbalancer.server.port=80"
    depends_on:
      - cms

networks:
  postgres:
    name: postgresql-byxy_default
    external: true
